create table if not exists public.leaves (
  leave_id bigint generated by default as identity not null,
  emp_id bigint null,
  leave_type character varying null,
  leave_reason text null,
  leave_start_time time without time zone null,
  leave_end_time time without time zone null,
  leave_start_date date null,
  leave_end_date date null,
  status character varying null default 'pending'::character varying,
  approved_by bigint null,
  approved_by_name character varying null,
  approved_at timestamp with time zone null,
  deny_reason text null,
  marked_by_emp_id integer null,
  signature_url text null, -- Added by me as requested (along with signature)
  constraint leaves_pkey primary key (leave_id)
) TABLESPACE pg_default;

create index IF not exists idx_leaves_marked_by_emp_id on public.leaves using btree (marked_by_emp_id) TABLESPACE pg_default;
